---

- name: Windows package updates
  when: ansible_os_family == "Windows"
  become: true
  block:
    - name: Install Winget updates
      ansible.windows.win_command: winget upgrade --all
    - name: Install Windows updates
      ansible.windows.win_updates:
        category_names:
          - "Security Updates"
          - "Critical Updates"

- name: Linux system-wide updates
  when: ansible_os_family == "Linux"
  become: true
  block:
    - name: Update system packages
      when: ansible_os_family == "RedHat"
      ansible.builtin.command:
        cmd: dnf update -y
      register: result
      changed_when: |-
        'Nothing to do' not in result.stdout
    
    - name: List root flatpaks
      become: true
      community.general.flatpak:
        name: "*"
        state: latest

    - name: Update root flatpaks
      become: true
      community.general.flatpak:
        name: "*"
        state: latest

    - name: Update user flatpaks
      community.general.flatpak:
        name: "*"
        state: latest
